// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Instruction } from "./Instruction";

export class Instructions {
  static encode(message: Instructions, writer: Writer): void {
    const instructions = message.instructions;
    for (let i: i32 = 0; i < instructions.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Instruction.encode(instructions[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Instructions {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Instructions();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.instructions.push(
            Instruction.decode(reader, reader.uint32())
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  instructions: Array<Instruction>;

  constructor(instructions: Array<Instruction> = []) {
    this.instructions = instructions;
  }
}
