// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

export enum OperationalStatus {
  BettingActive = 0,
  BettingPaused = 1,
  ClaimingPaused = 2,
  Paused = 3,
}
